config/routes.rb
Rails.application.routes.draw do
  resources :data do
    collection{ post :import }
    collection{ get 'classes'}
    collection{ get 'characteristics'}
    delete :destroy, on: :collection
  end

end

app/controllers/data_controller.rb
require 'csv'
class DataController < ApplicationController
  require 'PrimaryStatAnalysisCount/PrimaryStatAnalysisCount'
  @@data = []
  @@variation_range = []
  @@saved_variation_range = []
  @@anomaly = []

  before_action :set_datum, only: [:show, :edit, :update]
  # GET /data
  # GET /data.json

  def index
    if @@data != []
      @data = @@data
      @variation_range = @@variation_range
      PrimaryStatAnalysisCount.set_empirical_func(@@variation_range, @data.length)
      # session[:variation_range] = @variation_range
      #@classes = PrimaryStatAnalysisCount.create_classes(@variation_range, @data)
    end
  end

  def import
    @@data = []
    CSV.parse(params[:file].read) do |row|
      @@data << row[0].to_f
    end
    @@variation_range = PrimaryStatAnalysisCount.create_variation_range(@@data)
    redirect_to data_path, notice: 'Файл успішно завантажено'
  end

  def classes
    if @@data != []
      @data = @@data

      @class_numb = PrimaryStatAnalysisCount.count_classes_number(@data)
      @user_class_number = params[:user_class_number]
      p @user_class_number= @user_class_number.to_i
      if @user_class_number == 0
        @user_class_number = @class_numb
      end
      p @user_class_number

      @classes = PrimaryStatAnalysisCount.create_classes(@@variation_range,
                                                         @data, @user_class_number)
      PrimaryStatAnalysisCount.set_empirical_func(@classes, @data.length)
      @borders_arr = make_border_arr(@user_class_number, @classes)

      @relative_frequency_arr = make_rel_frequency_arr(@classes)
      @emp_func_arr = made_emp_func_arr
      @emp_func_class_arr = made_emp_func_class_arr(@classes)

    end
  end

  def make_border_arr(class_numb, classes)
    borders_arr = []
    (0...class_numb).each do |i|
      borders_arr << classes[i].a_border
    end
    borders_arr << @classes[@classes.length-1].b_border
  end

  def make_rel_frequency_arr(classes)
    relative_frequency_arr = []
    classes.each { |cl| relative_frequency_arr << cl.relative_frequency }
    relative_frequency_arr
  end

  def made_emp_func_arr
    arr = []
    @@variation_range.each do |x|
      arr << [x.value, x.empirical_func]
    end
    arr
  end

  def made_emp_func_class_arr(classes)
    arr = []
    classes.each do |cl|
      arr << [[cl.a_border, cl.empirical_func], [cl.b_border, cl.empirical_func]]
    end
    arr
  end

  def characteristics
    n = @@variation_range.length

    #Average
    sum = 0
    @@variation_range.each{|x| sum += (x.value * x.frequency)}
    @average_value = sum / n

    #Median
    @median = find_median

    #Dispersion
    sum = 0
    @@variation_range.each{ |x| sum += (((x.value - @average_value)**2 )*x.frequency)}
    @dispersion_shifted = (1.0 / n ) * sum
    @dispersion = (1.0 / (n - 1)) * sum

    #Medium-square
    @medium_square_shifted = Math.sqrt(@dispersion_shifted)
    @medium_square = Math.sqrt(@dispersion)

    #Pearson variation coefficient
    sum = 0
    @@variation_range.each{ |x| sum += (((x.value - @average_value)**2 )*x.frequency)}
    @pearson_coefficient = @medium_square / @average_value

    #Asymmetry coefficient
    sum = 0
    @@variation_range.each{ |x| sum += (((x.value - @average_value)**3 )*x.frequency)}
    @asymmetry_coefficient_shifted = (1.0 / (n *(@medium_square_shifted**3))) * sum
    @asymmetry_coefficient = Math.sqrt(n * (n - 1.0)) / (n - 2.0) * @asymmetry_coefficient_shifted

    #Coefficient of excess
    sum = 0
    @@variation_range.each{ |x| sum += (((x.value - @average_value)**4 )*x.frequency)}
    @excess_coefficient_shifted  = (1.0 / (n * (@medium_square_shifted**4))) * sum
    @excess_coefficient = (((n**2) - 1.0).to_f / ((n - 2.0)*(n - 3.0))) * ((@excess_coefficient_shifted - 3.0) * (6.0 / (n - 1.0)))

    #Contraccess coefficient
    @contraccess_coefficient = 1.0 / Math.sqrt(@excess_coefficient_shifted)

    #
    @average_value_ = @medium_square / Math.sqrt(n)
    @medium_square_ = @medium_square / Math.sqrt(2.0 * n)
    @pearson_coefficient_ = @pearson_coefficient * (Math.sqrt((1.0 + 2.0 * (@pearson_coefficient**2)) / (2.0 * n)))
    @asymmetry_coefficient_ = Math.sqrt((6.0 *(n - 2.0)) / ((n + 1.0) * (n + 3.0)))
    @excess_coefficient_ = Math.sqrt((24.0 / n) * (1.0 - (225.0 / (15.0 * n +124.0))))
    @contraccess_coefficient_ = Math.sqrt(@excess_coefficient.magnitude / (29.0 * n)) * ((@excess_coefficient**2 )- 1).abs**(3.0 / 4.0)

    #
    rozp_Studenta = find_rozp_Studenta
    @average_value_H = @average_value - rozp_Studenta * @average_value_
    @average_value_B = @average_value + rozp_Studenta * @average_value_

    @medium_square_H = @medium_square - rozp_Studenta * @medium_square_
    @medium_square_B = @medium_square + rozp_Studenta * @medium_square_

    @pearson_coefficient_H = @pearson_coefficient - rozp_Studenta * @pearson_coefficient_
    @pearson_coefficient_B = @pearson_coefficient + rozp_Studenta * @pearson_coefficient_

    @asymmetry_coefficient_H = @asymmetry_coefficient - rozp_Studenta * @asymmetry_coefficient_
    @asymmetry_coefficient_B = @asymmetry_coefficient + rozp_Studenta * @asymmetry_coefficient_

    @excess_coefficient_H = @excess_coefficient - rozp_Studenta * @excess_coefficient_
    @excess_coefficient_B = @excess_coefficient + rozp_Studenta * @excess_coefficient_

    @contraccess_coefficient_H = @contraccess_coefficient - rozp_Studenta * @contraccess_coefficient_
    @contraccess_coefficient_B = @contraccess_coefficient + rozp_Studenta * @contraccess_coefficient_

  #
    t1 = 2.0 + 0.2 * Math.log10(0.04 * n)
    t2 = (19.0 * (@excess_coefficient + 2)**(1.0/2.0) + 1)**(1.0/2.0)
    @a,@b = find_border(@asymmetry_coefficient, @average_value, t1, t2, @medium_square)
    @@anomaly = find_anomaly(@a ,@b)
    @anomaly = @@anomaly
  end

  def delete_anomaly(anomaly)
    @@saved_variation_range = @@variation_range
    anomaly.each do |x|
      @@variation_range.delete_at(@@variation_range.index(x))
    end
  end

  def find_border(a, x, t1, t2, s)
    a,b=0,0
    if (-0.2..0.2).include?(a)
      a = x - t1 * s
      b = x + t2 * s
    elsif a < -0.2
      a = x - t2 * s
      b = x + t1 * s
    elsif a < 0.2
      a = x - t1 * s
      b = x + t2 * s
    end
    return [a, b]
  end

  def find_anomaly(a, b)
    anomaly = []
    @@variation_range.each do |x|
      if (x.value<=a) || (x.value>=b)
        anomaly << x
      end
    end
    anomaly
  end

  def difference_in_degree(average, degree)
    sum = 0
    @@variation_range.each { |x| sum += ((x.value - average)**degree) * x.frequency}
    return sum
  end

  def find_median
    n = @@data.length
    @data = @@data.sort
    if (n % 2).zero?
        (@data[(n / 2) - 1] + @data[(n / 2)]) / 2.0
    else
        @data[(n / 2).to_i]
    end
  end

  def find_rozp_Studenta
    case @@data.length - 1
      when 24
        2.06
      when 69
        2.0
      else
        1.96
    end 
    


  end

  # GET /data/1
  # GET /data/1.json
  def show
  end

  # GET /data/new
  def new
    @datum = Datum.new
  end

  # GET /data/1/edit
  def edit
  end

  # POST /data
  # POST /data.json
  def create
    @datum = Datum.new(datum_params)

    respond_to do |format|
      if @datum.save
        format.html { redirect_to @datum, notice: 'Datum was successfully created.' }
        format.json { render :show, status: :created, location: @datum }
      else
        format.html { render :new }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data/1
  # PATCH/PUT /data/1.json
  def update
    respond_to do |format|
      if @datum.update(datum_params)
        format.html { redirect_to @datum, notice: 'Datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @datum }
      else
        format.html { render :edit }
        format.json { render json: @datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data/1
  # DELETE /data/1.json
  def destroy
    @@saved_variation_range = @@variation_range
    @@anomaly.each do |x|
      @@variation_range.delete_at(@@variation_range.index(x))
      end
    redirect_to data_path, notice: 'Аномалії успішно видалено'
  end

  helper_method :step_beck
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datum
      @datum = Datum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datum_params
      params.fetch(:datum, {})
    end
end

app/helpers/data_helper.rb
module DataHelper
end

app/views/data/_form.html.erb
<%= form_for(@datum) do |f| %>
  <% if @datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
      <% @datum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data/characteristics.html.erb
<h1>Characteristics</h1>
<a href=<%=classes_data_url%> class="previous">&laquo; Previous</a>
    <div class="container">
<table class="table table-bordered table-striped" style="width: 50%; float: left;">
  <tr class="info">
    <th></th>
    <th>Значення</th>
    <th>Середньоквадратичне відхилення</th>
    <th>Довірчий інтервал θн</th>
    <th>Довірчий інтервал θв</th>
  </tr>

      <tr>
        <td>Середнє арифметичне</td>
        <td><%= @average_value %></td>
        <td><%= @average_value_  %></td>
        <td><%= @average_value_H  %></td>
        <td><%= @average_value_B  %></td>
      </tr>

      <tr>
        <td>Медіана</td>
        <td><%= @median  %></td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
      </tr>

      <tr>
        <td>Середньоквадратичне</td>
        <td><%= @medium_square  %></td>
        <td><%= @medium_square_ %></td>
        <td><%= @medium_square_H%></td>
        <td><%= @medium_square_B%></td>
      </tr>

      <tr>
        <td>Коефіцієнт асиметрії</td>
        <td><%= @asymmetry_coefficient %></td>
        <td><%= @asymmetry_coefficient_ %></td>
        <td><%= @asymmetry_coefficient_H %></td>
        <td><%= @asymmetry_coefficient_B %></td>
      </tr>

      <tr>
        <td>Коефіцієнт ексцесу</td>
        <td><%= @excess_coefficient %></td>
        <td><%= @excess_coefficient_ %></td>
        <td><%= @excess_coefficient_H %></td>
        <td><%= @excess_coefficient_B %></td>
      </tr>

      <tr>
        <td>Коефіцієнт контрексцесу</td>
        <td><%= @contraccess_coefficient %></td>
        <td><%= @contraccess_coefficient_ %></td>
        <td><%= @contraccess_coefficient_H %></td>
        <td><%= @contraccess_coefficient_B %></td>
      </tr>

      <tr>
        <td>Коефіцієнт варіації</td>
        <td><%= @pearson_coefficient %></td>
        <td><%= @pearson_coefficient_ %></td>
        <td><%= @pearson_coefficient_H %></td>
        <td><%= @pearson_coefficient_B %></td>
      </tr>

</table>
</div>

<p>a=<%= @a %></p>
<p>b=<%= @b %></p>
<div>
  <table class="table table-bordered table-striped" style="width: 73%; float: right;">
    <tr class="info">
      <th>№ варіанти</th>
      <th>Значення варіанти</th>
      <th>Частота</th>
      <th>Відносна частота</th>
      <th>Значення емпіричної
        функції розподілу</th>
    </tr>
    <% @anomaly.each.with_index do |var_range, index| %>
        <tr>
          <td><%= index + 1%></td>
          <td><%= var_range.value%></td>
          <td><%= var_range.frequency%></td>
          <td><%= var_range.relative_frequency%></td>
          <td><%= var_range.empirical_func %></td>
        </tr>
    <% end%>
  </table>
</div>
<%= link_to 'Видалити аномалії', data_path, :confirm => 'Are you sure?', :method => :delete %>

app/views/data/classes.html.erb
<h1>Classes</h1>

<a href=<%=data_url%> class="previous">&laquo; Previous</a>
<a href=<%=characteristics_data_url%> class="next">Next &raquo;</a>

<h2>Рекомендована кількість классів - <%= @class_numb %></h2>


<%= form_tag({:controller => "data", :action => "classes"}, {:method => "get"}) do %>
  <label for="lookup">Кількість класів</label>
  <%= text_field_tag :user_class_number%>
<%= submit_tag "Задати" %>
<% end %>


<h2>Задана кількість классів - <%= @user_class_number %></h2>
<% if @data!=nil %>
    <div class="container">
<table class="table table-bordered table-striped" style="width: 50%; float: left;">
  <tr class="info">
    <th>№ варіанти</th>
    <th>Значення варіанти</th>
    <th>Значення варіанти2</th>
    <th>Частота</th>
    <th>Відносна частота</th>
    <th>Значення емпіричної
      функції розподілу</th>
  </tr>
  <% @classes.each.with_index do |i_class, index| %>
      <tr>
        <td><%= index + 1%></td>
        <td><%= i_class.a_border%></td>
        <td><%= i_class.b_border%></td>
        <td><%= i_class.frequency%></td>
        <td><%= i_class.relative_frequency%></td>
        <td><%= i_class.empirical_func%></td>
      </tr>
  <% end%>
</table>
<% end %>



</div>






<script>
    $(function () {
        $('#container_emp_func_var_range').highcharts({
            chart: {
                type: 'scatter',
                zoomType: 'xy'
            },
            title: {
                text: 'Height Versus Weight of 507 Individuals by Gender'
            },
            subtitle: {
                text: 'Source: Heinz  2003'
            },
            xAxis: {
                title: {
                    enabled: true,
                    text: 'Height (cm)'
                },
                startOnTick: true,
                endOnTick: true,
                showLastLabel: true
            },
            yAxis: {
                title: {
                    text: 'Weight (kg)'
                }
            },
            legend: {
                layout: 'vertical',
                align: 'left',
                verticalAlign: 'top',
                x: 100,
                y: 70,
                floating: true,
                backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF',
                borderWidth: 1
            },
            plotOptions: {
                scatter: {
                    marker: {
                        radius: 5,
                        states: {
                            hover: {
                                enabled: true,
                                lineColor: 'rgb(100,100,100)'
                            }
                        }
                    },
                    states: {
                        hover: {
                            marker: {
                                enabled: false
                            }
                        }
                    },
                    tooltip: {
                        pointFormat: '{point.x}, {point.y} kg'
                    }
                }
            },
            series: [{
                data: <%= @emp_func_arr %>
            }]
        });
    })
</script>






<div id="container_emp_func_var_range" class='container' style="min-width: 400px; height: 400px; margin: 0 auto"></div>




<script>
    $(function () {
        $('#container_histogram').highcharts({
            chart: {
                //type: 'column'
            },
            title: {
                text: 'Monthly Average Rainfall'
            },
            subtitle: {
                text: 'Source: WorldClimate.com'
            },
            xAxis: {
                gridLineWidth: 1,
                categories: <%= @borders_arr %>
            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Rainfall (mm)'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px"></span><table>',
                pointFormat:  '<b> {point.y:,.2f}</b>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: [
                {
                    name: 'Histogram',
                    type: 'column',
                    data: <%= @relative_frequency_arr << 0 %>,
                    pointPadding: 0,
                    groupPadding: 0,
                    pointPlacement: 'between'
                }



            ]
        });
    });
</script>



<div id="container_histogram" class='container' style="min-width: 400px; height: 400px; margin: 0 auto"></div>










<script>
    $(function () {

        (function (Highcharts) {

            var SplineSeries = Highcharts.seriesTypes.spline;

            // override the drawLine method
            var splineDrawGraph = SplineSeries.prototype.drawGraph;
            SplineSeries.prototype.drawGraph = function () {

                var arrowLength = 15,
                    arrowWidth = 8,
                    series = this,
                    segments = series.points,
                    lastPoint = segments[segments.length - 1],
                    nextLastPoint = segments[segments.length - 2],
                    angle = Math.atan((lastPoint.plotX - nextLastPoint.plotX) /
                        (lastPoint.plotY - nextLastPoint.plotY)),
                    path = [];

                if (angle < 0) {
                    angle = Math.PI + angle;
                }

                // call the original method
                splineDrawGraph.apply(series, arguments);

                console.log(path);
                lastPoint.plotX -= arrowLength - 1.5;

                // last point
                path.push('M', lastPoint.plotX, lastPoint.plotY);
                path.push(
                    'L',
                    lastPoint.plotX + arrowWidth * Math.cos(angle),
                    lastPoint.plotY - arrowWidth * Math.sin(angle)
                );
                path.push(
                    lastPoint.plotX + arrowLength * Math.sin(angle),
                    lastPoint.plotY + arrowLength * Math.cos(angle)
                );
                path.push(
                    lastPoint.plotX - arrowWidth * Math.cos(angle),
                    lastPoint.plotY + arrowWidth * Math.sin(angle),
                    'Z'
                );

                series.chart.renderer.path(path)
                    .attr({
                        fill: series.color
                    })
                    .add(series.group);

            };

        }(Highcharts));


        var chart = new Highcharts.Chart({

            chart: {
                renderTo: 'container_emp_func_class',
                type: 'spline'
            },

            plotOptions: {
              series: {
                  enableMouseTracking: false,
                  marker: {
                      enabled: false,
                      states: {
                          hover: {
                              enabled: false
                          }
                      }
                  }
              }
          },


            series: [
          <% @emp_func_class_arr.each do |x| %>
                {
                data: <%= x%>,
                marker: {
                    enabled: false
                }
            },
                <% end %>



            ]

        });
    })
</script>



<div id="container_emp_func_class" class='container' style="min-width: 400px; height: 400px; margin: 0 auto"></div>

app/views/data/edit.html.erb
<h1>Editing Datum</h1>

<%= render 'form' %>

<%= link_to 'Show', @datum %> |
<%= link_to 'Back', data_path %>

app/views/data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Завантаження даних</h1>
  <% if @data!=nil %>
    <a href=<%=classes_data_url%> class="next">Next &raquo;</a>
  <% end %>

<h3>Завантажити дані</h3>
<%= form_tag import_data_path(:file), multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag 'Завантажити дані'%>
<% end %>

<div class="container">
  <% if @data!=nil %>
      <table class="table table-bordered table-striped" style="width: 23%; float: left;">
        <tr class="info">
          <th >№</th>
          <th>x</th>
        </tr>

        <% @data.each.with_index do |datum, index| %>
            <tr>
              <td><%= index +1 %></td>
              <td><%= datum %></td>
            </tr>
        <% end %>

      </table>
      <table class="table table-bordered table-striped" style="width: 73%; float: right;">
        <tr class="info">
          <th>№ варіанти</th>
          <th>Значення варіанти</th>
          <th>Частота</th>
          <th>Відносна частота</th>
          <th>Значення емпіричної
            функції розподілу</th>
        </tr>
        <% @variation_range.each.with_index do |var_range, index| %>
            <tr>
              <td><%= index + 1%></td>
              <td><%= var_range.value%></td>
              <td><%= var_range.frequency%></td>
              <td><%= var_range.relative_frequency%></td>
              <td><%= var_range.empirical_func %></td>
            </tr>
        <% end%>
      </table>
  <% end %>

</div>

<br>

<%= link_to 'vud', data_path, :method => :destroy  %>

app/views/data/new.html.erb
<h1>New Datum</h1>

<%= render 'form' %>

<%= link_to 'Back', data_path %>

app/views/data/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_datum_path(@datum) %> |
<%= link_to 'Back', data_path %>